hotKey:
  # Hitting Shift-9 navigates to your namespaces view
  shift-9:
    shortCut:    Shift-9
    description: Viewing namespaces
    command:     namespaces
  # Hitting Shift-0 navigates to your pod view
  shift-0:
    shortCut:    Shift-0
    description: Viewing pods
    command:     pods
  # Hitting Shift-1 navigates to your deployments
  shift-1:
    shortCut:    Shift-1
    description: View deployments
    command:     dp
  # Hitting Shift-2 navigates to your xray deployments
  shift-2:
    shortCut:    Shift-2
    description: Xray Deployments
    command:     xray deploy
  # Hitting Shift-3 starts popeye
  shift-3:
    shortCut:    Shift-3
    description: Xray Deployments
    command:     popeye
