live_config_reload = true

import = [
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #  ~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[font.offset]
x = 1
y = 1

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "zsh"
args = ["-l", "-i", "-c", "tmux new-session -A -D -s CLI"]

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 1
blur = false
option_as_alt = "Both"

[window.dimensions]
columns = 170
lines = 50

[window.padding]
x = 5
y = 5

[window.position]
x = 200
y = 300
